app = 'tipdev'
primary_region = 'den'

[build]

[deploy]
  release_command = "bunx drizzle-kit migrate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
