name: Notify Fork

on:
    push:
        branches:
            - main

jobs:
    notify-fork:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger fork sync workflow
              run: |
                  curl -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.FORK_PAT }}" \
                    https://api.github.com/repos/dickeyy/tipdotdev/dispatches \
                    -d '{"event_type":"sync"}'
